// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbvySSk2JFrcg0QWmpTLP75tTM_Q9iQ7c',
    appId: '1:216607955152:web:f1cf73fc9dac3577c2a6d5',
    messagingSenderId: '216607955152',
    projectId: 'geminichatbot-8c742',
    authDomain: 'geminichatbot-8c742.firebaseapp.com',
    storageBucket: 'geminichatbot-8c742.firebasestorage.app',
    measurementId: 'G-5HX7CFFVST',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHZFzR30pS9DbQFLT28ZdzRjhwZiQJmqY',
    appId: '1:216607955152:android:c1ce6fad37f5de66c2a6d5',
    messagingSenderId: '216607955152',
    projectId: 'geminichatbot-8c742',
    storageBucket: 'geminichatbot-8c742.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0SUSb1GgHBvKLJFDKVkaSzztqFrMUM5E',
    appId: '1:216607955152:ios:760acfbd78980593c2a6d5',
    messagingSenderId: '216607955152',
    projectId: 'geminichatbot-8c742',
    storageBucket: 'geminichatbot-8c742.firebasestorage.app',
    iosBundleId: 'com.example.geminiApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0SUSb1GgHBvKLJFDKVkaSzztqFrMUM5E',
    appId: '1:216607955152:ios:760acfbd78980593c2a6d5',
    messagingSenderId: '216607955152',
    projectId: 'geminichatbot-8c742',
    storageBucket: 'geminichatbot-8c742.firebasestorage.app',
    iosBundleId: 'com.example.geminiApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDbvySSk2JFrcg0QWmpTLP75tTM_Q9iQ7c',
    appId: '1:216607955152:web:6cab3366607aeecec2a6d5',
    messagingSenderId: '216607955152',
    projectId: 'geminichatbot-8c742',
    authDomain: 'geminichatbot-8c742.firebaseapp.com',
    storageBucket: 'geminichatbot-8c742.firebasestorage.app',
    measurementId: 'G-KLJE1MHH07',
  );
}
